receivers:
  otlp:
    protocols:
      http:
        endpoint: '0.0.0.0:4318'
exporters:
  debug:
    verbosity: detailed
  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans
service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [debug]
    traces:
      receivers: [otlp]
      exporters: [debug, zipkin]
    logs:
      receivers: [otlp]
      exporters: [debug]